# Generated by Django 6.1.1 on 2026-09-27 16:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0002_imagenproducto'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orden', models.CharField(db_index=True, max_length=50, unique=True)),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('email_cliente', models.EmailField(max_length=254)),
                ('telefono_cliente', models.CharField(blank=True, max_length=30)),
                ('direccion_entrega', models.CharField(max_length=255)),
                ('ciudad', models.CharField(default='Santiago', max_length=100)),
                ('talla', models.CharField(default='M', max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_total', models.PositiveIntegerField(help_text='Total en CLP')),
                ('notas', models.TextField(blank=True)),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Pre-Orden Recibida & Confirmada'), ('CONFECCION', 'Confección y Bordado Artesanal'), ('CONTROL_CALIDAD', 'Control de Calidad & Autenticación VIP'), ('DESPACHO_DHL', 'Despacho Internacional DHL Express'), ('EN_ADUANA', 'En Aduana / Hub Local Santiago'), ('ENTREGADA', 'Entregada / Disponible para Retiro')], default='CONFIRMADA', max_length=30)),
                ('dhl_tracking', models.CharField(default='DHL-GB-88492019', max_length=60)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='preordenes', to='catalogo.producto')),
            ],
            options={
                'verbose_name': 'Pre-Orden / Pedido',
                'verbose_name_plural': 'Pre-Órdenes y Pedidos',
                'ordering': ['-fecha_creacion'],
            },
        ),
    ]
