# Generated by Django 6.1.1 on 2026-09-27 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0003_preorden'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='preorden',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Cuenta de cliente asociada de forma permanente', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='preordenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preorden',
            name='email_cliente',
            field=models.EmailField(db_index=True, help_text='Copia de respaldo siempre ligada', max_length=254),
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_pedido', models.CharField(db_index=True, max_length=50, unique=True)),
                ('email', models.EmailField(db_index=True, help_text='Copia de respaldo siempre ligada', max_length=254)),
                ('nombre_cliente', models.CharField(max_length=150)),
                ('telefono', models.CharField(blank=True, max_length=30)),
                ('direccion', models.CharField(max_length=255)),
                ('ciudad', models.CharField(default='Santiago', max_length=100)),
                ('talla', models.CharField(default='M', max_length=20)),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('precio_total', models.PositiveIntegerField(help_text='Total en CLP')),
                ('estado', models.CharField(choices=[('CONFIRMADA', 'Pre-Orden Recibida & Confirmada'), ('CONFECCION', 'Confección y Bordado Artesanal'), ('CONTROL_CALIDAD', 'Control de Calidad & Autenticación VIP'), ('DESPACHO_DHL', 'Despacho Internacional DHL Express'), ('EN_ADUANA', 'En Aduana / Hub Local Santiago'), ('ENTREGADA', 'Entregada / Disponible para Retiro')], default='CONFIRMADA', max_length=30)),
                ('notas', models.TextField(blank=True)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('fecha_estimada_entrega', models.DateField(blank=True, null=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos_producto', to='catalogo.producto')),
                ('usuario', models.ForeignKey(blank=True, help_text='Usuario propietario permanente del pedido', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pedido Oficial',
                'verbose_name_plural': 'Pedidos Oficiales',
                'ordering': ['-fecha_creacion'],
            },
        ),
        migrations.CreateModel(
            name='Tracker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(db_index=True, help_text='Copia de respaldo siempre ligada', max_length=254)),
                ('numero_guia', models.CharField(db_index=True, max_length=60, unique=True)),
                ('courier', models.CharField(default='DHL Express Priority', max_length=60)),
                ('estado_envio', models.CharField(default='En Tránsito Internacional', max_length=50)),
                ('ubicacion_actual', models.CharField(default='Hub Central London W12', max_length=100)),
                ('destino', models.CharField(default='Santiago, Chile', max_length=100)),
                ('porcentaje_avance', models.PositiveSmallIntegerField(default=35)),
                ('fecha_actualizacion', models.DateTimeField(auto_now=True)),
                ('pedido', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker', to='catalogo.pedido')),
                ('preorden', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='tracker_rel', to='catalogo.preorden')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='trackers', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Tracker / Seguimiento',
                'verbose_name_plural': 'Trackers / Seguimientos',
                'ordering': ['-fecha_actualizacion'],
            },
        ),
    ]
