# Generated by Django 6.1.1 on 2026-09-28 13:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0004_preorden_usuario_alter_preorden_email_cliente_pedido_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos_producto', to='catalogo.producto'),
        ),
        migrations.AlterField(
            model_name='preorden',
            name='producto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='preordenes', to='catalogo.producto'),
        ),
    ]
