# Generated by Django 6.1.1 on 2026-09-28 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0005_alter_pedido_producto_alter_preorden_producto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='estado',
            field=models.CharField(choices=[('CONFIRMADA', 'Pre-Orden Recibida & Confirmada'), ('CONFECCION', 'Confección y Bordado Artesanal'), ('CONTROL_CALIDAD', 'Control de Calidad & Autenticación VIP'), ('DESPACHO_DHL', 'Despacho Internacional DHL Express'), ('EN_ADUANA', 'En Aduana / Hub Local Santiago'), ('ENTREGADA', 'Entregada / Disponible para Retiro'), ('CANCELADA', 'Orden Cancelada & Stock Restituido')], default='CONFIRMADA', max_length=30),
        ),
        migrations.AlterField(
            model_name='preorden',
            name='estado',
            field=models.CharField(choices=[('CONFIRMADA', 'Pre-Orden Recibida & Confirmada'), ('CONFECCION', 'Confección y Bordado Artesanal'), ('CONTROL_CALIDAD', 'Control de Calidad & Autenticación VIP'), ('DESPACHO_DHL', 'Despacho Internacional DHL Express'), ('EN_ADUANA', 'En Aduana / Hub Local Santiago'), ('ENTREGADA', 'Entregada / Disponible para Retiro'), ('CANCELADA', 'Orden Cancelada & Stock Restituido')], default='CONFIRMADA', max_length=30),
        ),
    ]
