# Generated by Django 6.1.1 on 2026-09-28 13:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0006_alter_pedido_estado_alter_preorden_estado'),
    ]

    operations = [
        migrations.AddField(
            model_name='producto',
            name='codigo_estilo',
            field=models.CharField(blank=True, help_text='Código de estilo o SKU oficial', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='producto',
            name='color',
            field=models.CharField(blank=True, help_text='Colorway oficial', max_length=100, null=True),
        ),
    ]
