# Generated by Django 6.1.1 on 2026-09-29 01:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalogo', '0007_producto_codigo_estilo_producto_color'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pedido',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Usuario propietario permanente del pedido', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='preorden',
            name='usuario',
            field=models.ForeignKey(blank=True, help_text='Cuenta de cliente asociada de forma permanente', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='preordenes', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tracker',
            name='usuario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='trackers', to=settings.AUTH_USER_MODEL),
        ),
    ]
