# Generated by Django 6.1.1 on 2026-09-27 22:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('access_pin', models.CharField(blank=True, max_length=6, null=True, verbose_name='PIN de Acceso (OTP)')),
                ('pin_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Expiración del PIN')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cliente', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Cliente / Perfil OTP',
                'verbose_name_plural': 'Clientes / Perfiles OTP',
            },
        ),
    ]
