# Generated by Django 6.1.1 on 2026-09-28 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TicketSoporte',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código de Ticket')),
                ('nombre', models.CharField(max_length=150, verbose_name='Nombre del Solicitante')),
                ('email', models.EmailField(max_length=254, verbose_name='Email de la cuenta Solari ID')),
                ('contacto_alternativo', models.CharField(blank=True, max_length=150, verbose_name='WhatsApp o Contacto Alternativo')),
                ('motivo', models.CharField(max_length=255, verbose_name='Motivo del Problema')),
                ('mensaje', models.TextField(verbose_name='Detalle de la solicitud')),
                ('estado', models.CharField(choices=[('ABIERTO', 'Abierto'), ('EN_REVISION', 'En Revisión'), ('RESUELTO', 'Resuelto')], default='ABIERTO', max_length=20)),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Ticket de Soporte',
                'verbose_name_plural': 'Tickets de Soporte',
                'ordering': ['-creado_en'],
            },
        ),
    ]
