# Generated by Django 6.1.1 on 2026-09-28 01:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0002_ticketsoporte'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='ha_recibido_cupon',
            field=models.BooleanField(default=False, verbose_name='Cupón de Bienvenida Enviado'),
        ),
        migrations.AlterField(
            model_name='ticketsoporte',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Email de la cuenta SOLARY ID'),
        ),
    ]
