# Generated by Django 6.1.1 on 2026-09-28 03:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0003_cliente_ha_recibido_cupon_alter_ticketsoporte_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cupon_bienvenida_codigo',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Código de Cupón Único de Bienvenida'),
        ),
    ]
