# Generated by Django 6.1.1 on 2026-09-28 13:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0004_cliente_cupon_bienvenida_codigo'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='cupon_usado',
            field=models.BooleanField(default=False, verbose_name='Cupón de Bienvenida Usado'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='fecha_canje_cupon',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Fecha de Canje del Cupón'),
        ),
    ]
