# Generated by Django 6.1.1 on 2026-09-28 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuarios', '0005_cliente_cupon_usado_cliente_fecha_canje_cupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='bloqueado_hasta',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Bloqueado hasta'),
        ),
        migrations.AddField(
            model_name='cliente',
            name='intentos_fallidos',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Intentos fallidos de PIN'),
        ),
    ]
