# Generated by Django 6.1.1 on 2026-09-23 07:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Local',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('direccion', models.CharField(max_length=300)),
                ('horario', models.CharField(max_length=100)),
                ('telefono', models.CharField(max_length=20)),
                ('imagen', models.CharField(default='img/local1.jpg', max_length=255)),
                ('tipo', models.CharField(choices=[('FLAGSHIP', 'Flagship Store'), ('SHOWROOM', 'Showroom'), ('POP_UP', 'Pop-Up')], default='FLAGSHIP', max_length=20)),
                ('activo', models.BooleanField(default=True)),
                ('descripcion', models.TextField(blank=True)),
            ],
            options={
                'verbose_name': 'Local / Tienda',
                'verbose_name_plural': 'Locales / Tiendas',
                'ordering': ['nombre'],
            },
        ),
    ]
